FIX: spring-integration-amqp raises an exception creating appcontext
After upgrading spring-boot from 2.5.2 to 2.5.3, the
build started failing because it was not anymore able
to create the ApplicationContext.

The error reported was:

Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.<init>(Lorg/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer;)V
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)

The issue seems to be caused by this change in spring-integration-amqp:
https://github.com/spring-projects/spring-integration/commit/76f77ccd2c5f94e000495357e66c4f99fffc6010

Since the issue happens only due to the dependencies imported for testing it has been fixed rolling
back the library spring-integration-amqp the the previous version (5.5.1)